### PR TITLE
Added Heartrate app theming.

### PR DESCRIPTION
**Pull request by Kozova1**
This commit adds the option to change the color of the bars in the
heartrate app.

Signed-off-by: kozova1 <mug66kk@gmail.com>

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Similar to the feedback related to the clock I don't like the idea of theming each application individually.

A theme can offer a set of shades and colours that work together well but they should be named based on the character of the spot colour (bright, dull, etc) not the application that uses them.

For example

**Comment by daniel-thompson** [comment]
So... I've been doing a bit of work on the widgets over the holidays and ended up theming everything from slider-default together with some lightening code to generate lighter and darker shades.

On that basis I'm tempted to consolodate app theming down to (for now I think we will leave the status bar theming as it is):

* accent-hi
* accent-lo
* ui-default (this is what is currently called slider-default)
* ui-bright
* ui-contrast

ui-bright will default orange and be picked up the HRS app.
ui-constast is used to generate lighter/darker shades of ui-default and ui-bright and dictates how much different they will be from the normal case.

I also propose a generate accent-mid using the the lighten() code since it is only a tiny bit different to accent-lo anyway. However I'm not 100% sure about this so I will need to prototype it to check it leaves the default apps looking OK.

Any objections to picking up this work?

**Comment by Kozova1** [comment]
No problem - just don't forget to generate a default theme (to prevent unwanted crashes) :)

**Comment by daniel-thompson** [comment]
Sorry... I think I made an unusually grave typo.

I had meant to type: "Any objections to me picking up this work?" then it looks like I omitted the "me" which leaves that last sentance *very* ambiguous! Anyhow it looks like your reply assumed I would have a go at this even with the typo ;-) .

**Comment by daniel-thompson** [comment]
Hi @Kozova1 

I've been a bit brutal so I've pushed here to see what you think.

Daniel.

**Comment by daniel-thompson** [comment]
I didn't see any review comments so I've just pushed these changes to master because I want to shoot a video on the new apps and theming capabilities today!

**Comment by Kozova1** [comment]
Excited to see it :)

**Pull request merged**
