### PR TITLE
Notification Settings

### PR DESCRIPTION
**Pull request by Carglglz**
This PR adds a Notification level setting with four levels:
- Silent 
- Mid (40 ms pulse)
- High (225 ms pulse)
- Very High (450 ms pulse)

The Notification level can be adjusted with a slider widget.
This supersede #90

### CODE REVIEW

**Comment by cr0mbly** [comment]
keen to have this in master, am using it now.

**Comment by daniel-thompson** [comment]
Generally this looks like a good thing but I'm don't want to apply the "Very High" level.

It looks to me like the very high level is working around a bad PWM setting in the vibrator driver (P8 and PineTime motors are very different... currently the code treats them the same which makes the P8 vibrations far too weak).

**Comment by Carglglz** [comment]
> It looks to me like the very high level is working around a bad PWM setting in the vibrator driver (P8 and PineTime motors are very different... currently the code treats them the same which makes the P8 vibrations far too weak).

I wasn't aware of the difference, so I changed it back to three levels (0, 40, 80) for PineTime and (0,225,450) for P8, although it may be better to address this at driver level?

**Comment by daniel-thompson** [comment]
Merged! Thanks.

**Pull request closed without merging**
