### PR TITLE
Minification of code when uploading to the board.

### PR DESCRIPTION
**Pull request by yeyeto2788**
Changes done:

* Lint code to follow PEP8.

* Addition of the `requirements.txt`:
  * This is done for further addition of python libraries and install them all issuing only one command.

* Also changed the installation command on the documentation.

* Ignore virtual environment files and `.idea` folder from Jetbrains IDEs

**NOTE:** I have to say that I'm still waiting on my watch to arrive but the code should be working properly.

### CODE REVIEW

**Review by daniel-thompson — CHANGES_REQUESTED** [review]
There seem to be an enormous number of non-functional changes in this PR that are unrelated to the minimizer integration. Many appear to gratutious renaming and adding whitespace to functions that are not even modified in any other way.

These combine to make it tedious trying to find the minimiser changes amoung everything else. Non-functional refactoring, if it is done at all, should certainly not be combined in the same patch as functional changes.

**Comment by daniel-thompson** [comment]
Sorry. I forgot my manners! My review comments do still apply but ... thank you for the PR.

**Comment by yeyeto2788** [comment]
My bad, I was also trying to apply PEP8 linting. I have revert no needed changes and stick only on the minification of code in the `paste` method.

**Comment by daniel-thompson** [comment]
I've been running some tests and I'm afraid the minimizer isn't working on the real system. I think the way the minimizer joins lines is overflowing a maximum line length.

Original wasptool:

~~~
stingray$ ./tools/wasptool --device P8 --exec testcase.py --verbose
Ignoring PineTime (C4:79:ED:D4:18:51)
Ignoring PineTime (CB:2C:67:C7:60:68)
Connected to P8 (D5:C2:C9:27:46:DC).
Exit console using Ctrl-X.

>>> print("RFO""FOW")
print("RFO""FOW")
RFOFOW
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== icon = (
icon = (
===     b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?'
    b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?'
===     b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B'
    b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B'
===     b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
    b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
===     b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc25\xec4\xec5'
    b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc25\xec4\xec5'
===     b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
    b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
===     b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12'
    b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12'
===     b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10'
    b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10'
=== )
)
=== 
>>> wasp.system.run()
wasp.system.run()
Watch already running in the background
~~~

pyminifier wasptool:

~~~
stingray$ ./tools/wasptool --device P8 --exec testcase.py --verbose
Ignoring PineTime (C4:79:ED:D4:18:51)
Ignoring PineTime (CB:2C:67:C7:60:68)
Connected to P8 (D5:C2:C9:27:46:DC).
Exit console using Ctrl-X.

>>> print("HUJ""QYS")
print("HUJ""QYS")
HUJQYS
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== icon=(b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?' b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B' b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02' b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc25\xec4\xec5' b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02' b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12' b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10')
icon=(b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?' b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B' b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02xc2\x02' b'\xc2\x02\xc2\x02\xc2\x02\4\xec5' b'\xc2\x02\xc2\x02\xc2\x02\xx02\xc2\x02\xc2\x02' b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12' b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10')
=== 

=== 
Traceback (most recent call last):
  File "<stdin>"
SyntaxError: invalid syntax
>>> wasp.system.run()
wasp.system.run()
Watch already running in the background
~~~

**Comment by yeyeto2788** [comment]
Ohhh so sad to read that! I never had such issue. I'll see if there is an option to set max characters per line.

**Comment by yeyeto2788** [comment]
Hey @daniel-thompson, unfortunately, I could not find a way to set the maximum line character length. Can you send me the file you're trying to copy over the board?

**Comment by daniel-thompson** [comment]
The file is just the lines from the original wasptool output above:
~~~
icon = (
    b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?'
    b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B'
    b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
    b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc25\xec4\xec5'
    b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02'
    b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12'
    b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10'
)
~~~

**Comment by yeyeto2788** [comment]
Sorry for the delay in my reply.

When using just the changes I applied as you said it actually converts it into a really long string:

```python
icon=(b'D?\x1eB?\x17\x80\xee\x82\x02\x82\x06\x82\x02\x82?' b'\x0e\x88\x04\x88?\r\x88\x04\x88?\x0e\x82\x02\x82\x06B' b'\x02\x82?\x03\xc0\x89\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02' b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc25\xec4\xec5' b'\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02\xc2\x02' b'\xc2\x02\xc2\x02\xc2*B\x02B\x12\xc2\x06B\x06\xc2\x12' b'B\x02B\x1dH\x10\xc4\x04D\x04\xc4\x10H\x1cH\x10')
```

Using this [module](https://pypi.org/project/uminifier/) though it actually gets compressed into `.mpy` file format as the one attached within 
[this test.zip](https://github.com/daniel-thompson/wasp-os/files/5677980/test.zip) folder. Is there a way to transfer `.mpy` files to the board through serial?

**Comment by daniel-thompson** [comment]
> Is there a way to transfer `.mpy` files to the board through serial?

You can use wasptool as usual. However to transfer binary files you will need the `--binary` to ensure it gets ascii armoured before transfer.

BTW does minify-then-compile actually reduce the binary size compared to just a regular compile? Most of the passes in pyminifier don't really change how the compiler parses the input (except for the docstring strippping but mpy-cross can handle that already).

**Comment by yeyeto2788** [comment]
The minify would only get rid of docstrings, not needed spaces, and reduce other not needed characters within the code. I guess it would be easier and faster to do a compilation with fewer data.

**Comment by daniel-thompson** [comment]
Ok. The .mpy route is now documented (https://wasp-os.readthedocs.io/en/latest/appguide.html#uploading-in-binary-form ) so I'll close this PR.

**Pull request closed without merging**
